#!/bin/bash -eux

pushd "$(git rev-parse --show-toplevel)"
DATA_IN="./data/all.zip"
OUTPUT_PATH="./data/data_train.csv"

dvc run \
-d $DATA_IN \
-o $OUTPUT_PATH \
./extract_dataset.py --subset test \
                     --data-in $DATA_IN \
                     --output-path $OUTPUT_PATH
popd









